### ISSUE TITLE
Not working on wsl2

### ISSUE THREAD

**Issue by l-sannin** [WaylonWalker/waylonwalker.com#4]
On wsl2 the uname -r command returns '5.10.16.3-microsoft-standard-WSL2', changing to:
`
if system('uname -r') =~ "microsoft"
    augroup Yank
        autocmd!
        autocmd TextYankPost * :call system('/mnt/c/windows/system32/clip.exe ',@")
        augroup END
endif
`
Works again

**Comment by WaylonWalker** [comment]
Thanks for sharing, This will be handy if I ever use wsl2,

**Comment by WaylonWalker** [comment]
I just updated this post reflecting your feedback.

https://waylonwalker.com/vim-wsl-clipboard/
