### ISSUE TITLE
A Good Use for global .gitignore

### ISSUE THREAD

**Issue by cl3m3c7** [WaylonWalker/waylonwalker.com#6]
Hi there,
I don't know how to contact you, but I just want to share with you how to be able to stow .gitignore directly instead of using the .global_gitignore hack by providing --dotfiles flag: 

``` 
mv git/.global_gitignore git/dot-gitignore
stow git --dotfiles
```

hope this helps ^^

**Comment by WaylonWalker** [comment]
Thanks for sharing!  I am not quite sue why I chose .global_gitignore.
